enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  '@mui/x-date-pickers@*':
    dependencies:
      react-dom: '*'
  chalk@*:
    dependencies:
      '#ansi-styles': 'npm:ansi-styles@*'
      '#supports-color': 'npm:supports-color@*'
  material-ui-popup-state@*:
    dependencies:
      react-dom: '*'
  npm-check-updates@*:
    dependencies:
      ini: '*'
  stylelint-config-recommended-scss@*:
    dependencies:
      postcss: '*'
  stylelint-config-xo-scss@*:
    dependencies:
      postcss: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

pnpEnableEsmLoader: true

pnpEnableInlining: true

pnpFallbackMode: dependencies-only

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.2.3.cjs
